### ISSUE TITLE
Problem with data preprocess

### ISSUE THREAD

**Issue by newace0127** [CVxTz/EEG_classification#3]
Hello Youness,

Thank you so much for your contribution. I got the following error when trying to run the prepare_physionet.py:

Traceback (most recent call last):
File "prepare_physionet.py", line 15, in 
from mne import Epochs, pick_types, find_events
File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne_init_.py", line 22, in 
from .utils import (set_log_level, set_log_file, verbose, set_config,
File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne\utils_init_.py", line 23, in 
from .fetching import _fetch_file, _url_to_local_path
File "L:\Programs\anaconda3\envs\env_py2\lib\site-packages\mne\utils\fetching.py", line 11, in 
from urllib import parse, request
ImportError: cannot import name parse

It seems the dependency library is out of date? Is there any way to counter the problem?
Thank you so much.

**Comment by CVxTz** [comment]
Hello,

That script is just copied from https://github.com/akaraspt/deepsleepnet for convenience and should be run with **python 2** unlike the Machine learning part of the repo.

Did you run it with python 2 ?

**Comment by newace0127** [comment]
Oh I figured it out. I did run with py2, the problem was the dependency lib mne. The code required a specific old version of mne instead of the latest one.
Thank you for your great contribution!

**Comment by balandongiv** [comment]
Hi, may I know what version of mne work for the data pre-process part?
